QuadTree Frontend
googleinterns/step100-2020 pull request #50
Opened 2020-07-30 18:05 UTC by anikabagga

- Filter nearest locations by closest 1/5/10/15/20 places
- Places displayed on Google Map with markers for each location 

Note: Haven't merged by previous branch yet, so some files may be outdated. 

![Screenshot 2020-07-30 at 11 02 13 AM](https://user-images.githubusercontent.com/16986213/88957770-48483900-d254-11ea-924a-ba9879abc956.png)

2020-07-31 13:42 UTC, lxcyqx commented
I think the binary files should be excluded

2020-07-31 21:26 UTC, nicorod-google requested changes

2020-07-31 21:26 UTC, nicorod-google commented on capstone/.gitignore
> +*.json
I'd recommend changing this to api_key.json, there might be instances where you want to include json but your excluding all of them

2020-07-31 21:26 UTC, nicorod-google commented on capstone/src/main/java/com/google/sps/Objects/Coordinate.java
> +public final class Coordinate implements Serializable{
nit: space after "Serializable"

2020-07-31 21:26 UTC, nicorod-google commented on capstone/src/main/java/com/google/sps/Objects/Location.java
> +public final class Location implements Serializable{
nit: space after "Serializable"

2020-07-31 21:26 UTC, nicorod-google commented on capstone/src/main/webapp/scripts/group.js
> +  }
You can use parseInt() to convert these to numbers instead so you don't if statements for each value you want

2020-07-31 21:26 UTC, nicorod-google commented on capstone/src/main/webapp/scripts/map.js
> +function toggle_location_visibility() {
nit: camel case

2020-07-31 21:26 UTC, nicorod-google commented on capstone/src/main/java/com/google/sps/servlets/QuadTreeServlet.java
> +      getServletContext().getResourceAsStream("/WEB-INF/fast-food-location.csv"));
Can you add the CSV name as a constant? Will make this less dependent on this dataset and allow you to swap datasets if you wanted to

2020-07-31 21:55 UTC, nicorod-google approved these changes

2020-08-03 14:50 UTC, nicorod-google approved these changes

2020-08-03 15:32 UTC, merged